### ISSUE TITLE
should we update crontab schedule to something less heavy

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/d2-manifest-bot#28]
1700 is 9am PST

```
  schedule:
    ## - cron: '*/5 * * * *' ## currently running every 5 minutes every day.
    - cron: '*/5 17-23 * * 2,5' ## every 5 minutes tuesday and friday between 1700 and 2300 UTC
    - cron: '5 * * * 0,1,3,4,6,7' ## at 5 minutes passed the hour on every other day
    - cron: '5 0-16 * * 2,5' ## 5 minutes passed the hour until 1700 on tuesday and fridays
```
